name: dem_recip_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  flutter_secure_storage: ^9.0.0
  fluttertoast: ^8.2.5
  shared_preferences: ^2.0.6
  flutter_chat_ui: ^1.6.12
  image_picker: ^1.1.1
  file_picker: ^8.0.3
  uuid: ^4.4.0
  open_filex: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  provider: ^6.0.1
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1

flutter:
  uses-material-design: true
  assets:
    - assets/messages.json
